global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - api_version: v2
    static_configs:
    - targets:
      - alertmanager:9093

rule_files:
- "rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'alertmanager'
    static_configs:
    - targets:
      - alertmanager:9093
  - job_name: 'nginx'
    static_configs:
    - targets:
      - nginx_exporter:9113
  - job_name: 'realworld'
    static_configs:
    - targets:
      - backend:8585
